services:
  - type: web
    name: hrms-lite-api
    env: python
    buildCommand: pip install -r requirements.txt
    runtime: python-3.11.9
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
